# Generated by Django 5.0 on 2024-07-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Imagen')),
                ('Nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('rubro', models.TextField(max_length=120, null=True, verbose_name='Imagen')),
            ],
        ),
    ]
